spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa # do zrobienia zadania należy postawić bazę jpa na postgres
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        show-sql: true
  liquibase:
    change-log: classpath:db/change-log.yml